# Numpy学习笔记

## ndarray
ndarray是numpy中的多维数组对象，是一个快速而灵活的大数据集容器。用来执行一些数据运算，其语法跟标量元素之间的运算一样
### 1.创建ndarray  
创建方法很简单，用以下函数即可创建:  

**array** - 创建一个ndarray，可通过dtype指定数据格式，可以通过输入数据推断数据格式  
**asarray** - 将输入数据转为ndarray  
**arange** - 生成一个range范围内的递增数组  
**ones, zeros, eye** - 生成全1、全0、单位矩阵  
**empty** - 生成空矩阵，不初始化


In [1]:
import numpy as np

In [2]:
a = [1,2,3]
print("array: \n", np.array(a, dtype=np.float32))
print("asarray: \n", np.asarray(a, dtype = np.float64))
print("arange: \n", np.arange(1, 10,dtype = np.float64))
print("zeros: \n", np.zeros([1,2,3],dtype = np.float64))
print("ones: \n", np.ones([1,2,3],dtype = np.float64))
print("eye: \n", np.eye(3, dtype = np.float64))
print("empty: \n", np.empty([1,2,3],dtype = np.float64))

array: 
 [ 1.  2.  3.]
asarray: 
 [ 1.  2.  3.]
arange: 
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
zeros: 
 [[[ 0.  0.  0.]
  [ 0.  0.  0.]]]
ones: 
 [[[ 1.  1.  1.]
  [ 1.  1.  1.]]]
eye: 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
empty: 
 [[[ 1.  1.  1.]
  [ 1.  1.  1.]]]


# 2.数据类型  
numpy的数据类型一共有一下几种:  
![image](./numpy_datatype.jpeg)  
除了上面的以外，还有```string_```或```str_```，对应着字符串，类型代码为S。  
如果转换失败了，会抛出```TypeError```异常。

In [3]:
origin_arr = np.array([a, a, a], dtype=np.float32)
print(origin_arr.dtype)

#转换np.float32类型为字符串类型
print(origin_arr.astype(np.str_))


float32
[['1.0' '2.0' '3.0']
 ['1.0' '2.0' '3.0']
 ['1.0' '2.0' '3.0']]


## 3. 数组和标量的运算  
维度相等的数组进行标量运算，则标量运算都会应用到元素级，也就是说，对应位置的元素进行标量运算。不同维度的数组之间的运算称为**广播（broadcast）**，后面再说……

In [4]:
# 1*1, 2*2, 3*3
arr = origin_arr.copy()
print(origin_arr * origin_arr)

#该操作会广播至a[0]中的每个元素
arr[0] = 10
print(arr)

[[ 1.  4.  9.]
 [ 1.  4.  9.]
 [ 1.  4.  9.]]
[[ 10.  10.  10.]
 [  1.   2.   3.]
 [  1.   2.   3.]]


## 3.基本的切片和索引  
numpy里的```ndarray```和python中的list很相似，但是在切片的时候，全部是$\underline{引用，没有拷贝}$，如果想用拷贝，请使用```copy```函数，例子如下:

In [5]:
#切片
arr = np.arange(1, 10, dtype=np.float32)
print(arr[2:5])#简单的切片示例

#切片是引用
x = arr[2:5]
x[1] = 30

print(arr)
print(x)

[ 3.  4.  5.]
[  1.   2.   3.  30.   5.   6.   7.   8.   9.]
[  3.  30.   5.]


In [6]:
#索引
arr2d = np.array([[0]*3, [1]*3, [2]*3])
#第1行，第一列
print(arr2d)
print(arr2d[1][1])
print(arr2d[1, 1])

print(arr2d[2,1])

#3d 2*2*3
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("arr3d: \n", arr3d)
#广播演示
x = arr3d.copy()
x[0] = 43
print("x: \n", x)
print("arr3d[1,1]:\n", arr3d[1,1])

[[0 0 0]
 [1 1 1]
 [2 2 2]]
1
1
2
arr3d: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
x: 
 [[[43 43 43]
  [43 43 43]]

 [[ 7  8  9]
  [10 11 12]]]
arr3d[1,1]:
 [10 11 12]


### 切片索引  
切片索引可以很好的找到某一特定维度或特定范围内的所有元素，而不用像python中那样用循环查找,可以非常方便地选出区域

In [7]:
#选出arr3d中
print('arr3d:\n',arr3d)
print('arr3d[:, 1, 1:]:\n', arr3d[1:, :, 1:])

arr3d:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
arr3d[:, 1, 1:]:
 [[[ 8  9]
  [11 12]]]


### 布尔索引  
numpy中可以使用```array > n```这种方法将数组转化为boolean形式的数组，当然，操作符可以是```==, >=, <=, !=,  and, or, not, &, |, ~```,通过boolean数组b，可以使用```array[b]```来返回array中所有b中为True的位置上的元素。（其实这个概念不太好解释，还是看代码）

In [17]:
print("arr3d:\n",arr3d)

b = arr3d > 10
print("\n\nb > 2:\n", b)
print("\n\narr3d[b]:\n", arr3d[b])

arr3d:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


b > 2:
 [[[False False False]
  [False False False]]

 [[False False False]
  [False  True  True]]]


arr3d[b]:
 [11 12]


通过boolean数组进行变量赋值也是可以的

In [18]:
arr3d_copy = arr3d.copy()
arr3d_copy[b] = 100
print('arr3d_copy:\n', arr3d_copy)

arr3d_copy:
 [[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10 100 100]]]
